import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: 'Attendence Management System',
  description: 'Generated by create U Developers',
  icons: {
    icon: { url: "/logo.png", type: "image/jpg" }
  },

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
